# Generated by Django 5.0.6 on 2024-06-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_search_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='user.search')),
            ],
        ),
    ]
