# Generated by Django 5.0.6 on 2024-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_product_search_product_user_delete_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
